[book]
title = "DM By Example"
description = "A guide to DM in the style of Rust by Example."
authors = ["ZeWaka"]
language = "en"
src = "src"

[output.html]
default-theme = "dark"

#[output.html.fold]
#enable = true
